### ISSUE TITLE
SWIM overrides the SUCC button that cancels the roll to unshake script[BUG] 

### ISSUE THREAD

**Issue by grendel111111** [SalieriC/SWADE-Immersive-Macros#100]
**Describe the bug**
When SUCC has the disable condition removal check box is checked and SWIM is active it shows the default roll to unshake/unstun  box
**To Reproduce**

**Expected behavior**
If the SUCC disable condition removal check box is checked the unstun/unshake macros shouldn't run at the start of the players turn.
**Screenshots**
![image](https://user-images.githubusercontent.com/80164119/199243461-892452b1-6bad-4c52-aa5c-a51fb3682a27.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser: chrome
 - FVTT Version: 10.288
 - SWADE System Version: 2.0.6
 - SWIM Version:  1.0.0
 - Other Modules enabled?:  [no, just SUCC]

**Comment by SalieriC** [comment]
Thank you for that. I've totally missed it. It's done in git and will be available in the next version.
