### ISSUE TITLE
[FEATURE] Fear Table Macro - use a benny before fear table result

### ISSUE THREAD

**Issue by Arnok13** [SalieriC/SWADE-Immersive-Macros#105]
**Is your feature request related to a problem? Please describe.**
the macro won't let the player use a benny without seeing the fear effect (and if it is an Adrenaline Surge she will be pleased)

**Describe the solution you'd like**
a way to ask for a reroll in case of a failure, before rolling the result on the fear table.

**Describe alternatives you've considered**
two macros : one for the Fear test and another for the fear table (not quite a good alternative but can do the job)

**Additional context**
none.

**Comment by SalieriC** [comment]
Thank you for your time. =)
Currently the macro is intended as a GM macro, not a player macro that rolls Spirit to resist Fear. That might become a feature in the future but right now that is not the scope of this macro. The intended use is: Players roll against Fear. Those who fail will be targeted by the GM (while the source of Fear is selected) and then the macro will apply the appropriate effects.
I will leave this open as I might change/extend its functionality in the future. (I don't know how likely that is atm as there are a ton of edges that change how rolls against Fear work, especially in Deadlands. The Horror Companion and Pinebox may add even more. To take those into account would be very difficult.)

**Comment by SalieriC** [comment]
Yeah, I think I'll keep the functionality as it is. I'm sorry to disappoint you but that is currently way too much work for limited gain. I might come up with a different (way better) solution to this but that's currently not possible due to a severe lack of time.
Thank you for the suggestion though. =)
