### ISSUE TITLE
Healing Spells, Regeneration and Healing Potion

### ISSUE THREAD

**Issue by Alexsist** [SalieriC/SWADE-Immersive-Macros#108]
Are there detailed instructions on how to link a personal medical center macro to a magic skill? So the character heals his own or someone else's wounds when using the skill. 

I just can't figure out how to create healing potions, regeneration or spells

**Comment by SalieriC** [comment]
In which way? Like executing the macro if s/o heals? Or adding the roll to the macro itself?
