### ISSUE TITLE
[BUG] Arcane Protection not reducing damage of damaging powers

### ISSUE THREAD

**Issue by sroakjp** [SalieriC/SWADE-Immersive-Macros#111]
**Describe the bug**
RAW arcane protection should apply a penalty to affect the targeted character, and should reduce damage if the power inflicts damage. The penalty to affect the target is being applied as expected, but damage isn't being reduced. I tested this with the Bolt power.

**Expected behavior**
If the targeted token has Arcane protection the roll to affect them with a power should be reduced, and damage from the power should be reduced by the same amount.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - FVTT Version: 10.291
 - SWADE System Version: 2.1.7
 - SWIM Version:  1.2.3
 - Other Modules enabled?:  yes
 - 
![image](https://user-images.githubusercontent.com/62338951/210121583-aa49eb3c-7d9a-4f8e-a76a-5bbcac3cf055.png)
![image](https://user-images.githubusercontent.com/62338951/210121598-ee724bbc-abcf-41fb-9a59-144c42417e95.png)
![image](https://user-images.githubusercontent.com/62338951/210121610-18810bd8-2d23-4e43-9329-6887b03c7be4.png)

**Comment by SalieriC** [comment]
Thank you, it must've been an oversight. It's fixed in git and will be part of the next release.
