### ISSUE TITLE
[BUG] Effect Builder labeling Damage Field as Arcane Protection

### ISSUE THREAD

**Issue by Gallumph** [SalieriC/SWADE-Immersive-Macros#115]
**Describe the bug**
When using the Effect Builder, if you do a standard Damage Field (the 2d4 version), the Active Effect is listed as 'Arcane Protection(2d4)'.  If you do the upgraded version, it is correct and shows 'Damage Field (2d6)'.  I checked the effect_builder.js and it looks like a simple text error for that result (manually correcting it in the file fixed the issue).

**To Reproduce**
1. Select Token and Target for Active Effect
2. Select Damage Field (not upgraded)
3. Active Effect on target is listed as 'Arcane Protection(2d4)

**Expected behavior**
The Active Effect should be 'Damage Field(2d4)'

 - FVTT Version: 10.291
 - SWADE System Version: 2.2.3
 - SWIM Version:  1.2.3

**Comment by SalieriC** [comment]
Yep, a copy-paste error it seems. It's using the wrong translation string here: https://github.com/SalieriC/SWADE-Immersive-Macros/blob/b5e4964ac7d5a624f52f83babda376bbd3026e17/swim/scripts/swim_modules/effect_builder.js#L1463

Thank you for the report, will fix it in the next version.

**Comment by SalieriC** [comment]
Done. Will be available in the next release.
