### ISSUE TITLE
[NEW POWER] Modify Boost/Lower trait to support more functionality

### ISSUE THREAD

**Issue by bloy** [SalieriC/SWADE-Immersive-Macros#118]
**Power**
Boost/Lower trait builder enhancements:
- support the greater and strong modifiers
- name separate boosts/lowers differently
- provide separate effects for the lower trait and the major lower trait from a raise

detail:
- Name effects eg "Boost Agility" or "Lower Fighting", to allow them to be distinguished on the character sheet
- if lower is cast with a raise, create "major boost trait" and "minor boost trait" with a sides -2 on each, to handle if the target shakes off the raise and but not the primary effect.
- additional modifiers as noted below

**Modifiers**
- Greater:  For Boost, selected trait gets a free reroll each round. For lower, affected trait rolled at -2
    - boost: change the name of the effect to include "greater" or "free reroll" as a reminder
    - lower: apply an additional modifier -2 effect to the primary effect
- Strong: (lower only) spirit roll to shake off the effect is -2
    - add "Strong" to the effect name as a reminder.

**Setting**
Savage Pathfinder & SWADE Fantasy Companion

**Comment by SalieriC** [comment]
Thank you for your time.
This requires some work on the API of SUCC first and that is currently in the process of being rewritten. So don't expect it anytime soon.

**Comment by bloy** [comment]
if you don't mind pull requests, I was considering trying to hack at it a little bit this weekend, but if you have a big rewrite in mind I don't want to get in the way of that.

**Comment by SalieriC** [comment]
I don't mind you saving me time at all. :D
Feel free to take a look at SWIM but SUCC is currently undergoing major changes and it is thus unlikely any PRs to the current module will make it into the new version.
The problem with this feature is that I did not think about changing all properties of an AE when the data is passed to the SUCC API. Thus the label of an AE can currently not be changed using the SUCC API. This would've been a thing of a few minutes but the rework has to take priority ofc.

An alternative would be to get the effect after creation and then simply update it in SWIM but that's hacky and enhancing the SUCC API seems to be the better solution.

**Comment by SalieriC** [comment]
Closed due to inactivity. Feel free to reopen if you come up with a good solution.
