### ISSUE TITLE
[FEATURE] Add a setting to disable the Scene Control Buttons

### ISSUE THREAD

**Issue by mclemente** [SalieriC/SWADE-Immersive-Macros#121]
Please, add a setting to disable the Scene Control Buttons. I don't use them but there's no way to disable them.

Consider these options:
- Add a 3-way setting with "None", "Token Controls" and "Separate SWIM Control" options, so users can set them as they like.
- Add them as keybindings.

Here's how cluttered my Token Controls is with just 4 modules (Challenge Tracker, SWIM, Hourglass, Sequencer). Of those, I can disable Sequencer's or even move them to their own control button (the last button on the left)
![image](https://user-images.githubusercontent.com/5288872/235280343-ce558b2d-e4da-40eb-b02f-20b62e318eba.png)

**Comment by SalieriC** [comment]
That you call cluttered? 🤣 
But I hear ya, The combat setup button will probably go anyway (for now at least) as the code is somewhat buggy and hard to maintain. Then the only button left would be the plus (raise calculator). Would that still be too much for your taste? I'm not sure how easy it would be to add a new setting for this so I need to look into it.

**Comment by mclemente** [comment]
Considering the default is just the first 3 buttons, it is an issue when every module adds a button to I end up with 9.

For a setting you'd need to move `register_settings` up to the setup hook and move the Hook to getSceneControlButtons inside it.

Example:
```js
Hooks.on('setup', () => {
  api.registerFunctions();
  register_settings();
  if (game.settings.get("swim", "addHudButtons") {
    Hooks.on('getSceneControlButtons', function (hudButtons) {
      swim_buttons(hudButtons)
    });
  }
})
```

You could also turn it into a keybind like this:

```js
game.keybindings.register("swim", "raiseCalculator", {
		name: "SWIM.openRaiseCalculatorName",
		hint: "SWIM.openRaiseCalculatorHint",
		onDown: () => {
			// Entire onClick from the Calculator
		},
		restricted: true,
		precedence: CONST.KEYBINDING_PRECEDENCE.NORMAL,
	});
```
If you do, I advise you move the onClick to its own function so you don't duplicate code between the button and the keybind.

**Comment by SalieriC** [comment]
Done in Git. Thanks a lot for your work. =)
