### ISSUE TITLE
[FEATURE] Add option to set duration on Master Summoner

### ISSUE THREAD

**Issue by steveculshaw** [SalieriC/SWADE-Immersive-Macros#124]
Add a mechanism to allow setting the duration of the active effect to something other than the default 5 rounds, e.g., to 5 minutes. 

Preference would be linked checkboxes with the three values for duration from Fantasy Companion, i.e., 5 rounds, 5 minutes and 1 hour. The duration of the summoning would be set as appropriate.

A selection list with the values, but selecting is a slower UI than just clicking a check box.

In the Fantasy Companion, the Summoner's summons last for 5 minutes, and the Druid' s last for 1 hour.

**Comment by SalieriC** [comment]
I was thinking about just checking for edges as usual and set the duration like this. Checkboxes will make the dialogue somewhat more confusing for less tech-savvy players I fear. A selector would probably my go-to if you're not in favour of the edge filtering method.

**Comment by steveculshaw** [comment]
I'd not appreciated you could check for edges.
Certainly if you can simplify using this approach, go for it 👍

Is there anyway to put the edge name / duration in a configurable option? I've made a home brew fantasy, and I'm worried my edge name's wouldn't match the official Fantasy Companion when it's released for FVTT

**Comment by steveculshaw** [comment]
You're right ... I'm being over cautious 😅
I mean it's maybe 3 players who have to change 1 edge, and I've matched the names in the FC PDF, so hopeful Pinnacle don't do something very weird with the official edge names, I should be good 😁

**Comment by SalieriC** [comment]
Okay so "Master Summoner" (which is part of Summoner) doesn't seem to apply here as it only reduces the cost of the powers by 2, not increase the duration. Unless my version is somehow outdated (but I doubt it as I just downloaded it). Could you please double check that?
As for Druid it is as you describe and also increases the duration of shape change.

**Comment by steveculshaw** [comment]
Ere, confused ...
Just downloaded a fresh copy of v1.6 and it says ... 
_MASTER SUMMONER: A summoner reduces the cost of summon ally, summon animal, and summon monster by 2 (to a minimum of 1), and the spells’ Durations are measured in **minutes** rather than rounds._
So 5 rounds becomes 5 minutes ?

**Comment by SalieriC** [comment]
Must've missed that yesterday. Tired and all.
I'll get to it.
