### ISSUE TITLE
[BUG] The extend dialog for the Mighty Summoner has "undefined"

### ISSUE THREAD

**Issue by steveculshaw** [SalieriC/SWADE-Immersive-Macros#127]
**Describe the bug**
After casting the Summon Animal power using the Mighty Summoner macro, the dialog for resetting the duration is showing "Remove undefined from character" ...

![image](https://github.com/SalieriC/SWADE-Immersive-Macros/assets/64320/1f8919fc-ecd6-4911-8d55-96241ccb2512)

**To Reproduce**
Steps to reproduce the behaviour:
1. Summon Animal with duration 5 rounds 
2. Click through 6 rounds
3. Dialog for extending power duration appears
4. See "undefined" error

**Expected behaviour**
The "undefined" to refer to _something_, not sure what? ... the name of the Power?

**Desktop (please complete the following information):**
OS: [Windows 11]
SWIM: [1.5.0]
SUCC: [2.0.0]
Swade System: [3.0.4]
Foundry VTT: [11.302]
Browser: [Google Chrome 114.0.5735.134]
Other modules: BR2

**Additional context**
N/A

**Comment by SalieriC** [comment]
I'll look into it, thanks. =)

**Comment by SalieriC** [comment]
I can reproduce it but I have no clue what's wrong. Gotta need help with that.
It might also be a bug in the SWADE system so if you're able to reproduce it elsewhere please let me know.

**Comment by steveculshaw** [comment]
Will see if I can repo it 👍

**Comment by SalieriC** [comment]
Turned out to be a bug in SWADE. I've created a PR that aims to fix this issue: https://gitlab.com/peginc/swade/-/merge_requests/386

**Comment by steveculshaw** [comment]
Nice one 

And thanks for resolving
