### ISSUE TITLE
[BUG] The Unshake macro Shakes a character if they aren't already Shaken

### ISSUE THREAD

**Issue by steveculshaw** [SalieriC/SWADE-Immersive-Macros#129]
**Describe the bug**
If the player runs the Unshake macro when they are NOT shaken, they get the Shaken status.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select character, and make sure they are NOT Shaken
2. Run the Unshake macro
3. Check the character sheet

**Expected behaviour**
When a character is NOT already shaken, running the macro would have no effect

**Screenshots**
N/A

Desktop (please complete the following information):
OS: [Windows 11]
SWIM: [1.5.0]
SUCC: [2.0.0]
Swade System: [3.0.4]
Foundry VTT: [11.302]
Browser: [Google Chrome 114.0.5735.134]
Other modules: BR2

Additional context
N/A

**Comment by SalieriC** [comment]
That is intended bahaviour and has always been: https://github.com/SalieriC/SWADE-Immersive-Macros/wiki/Macros#un-shake
That's why it is officially referred to as the (Un-)Shake macro. =)
