### ISSUE TITLE
Evaluate PC Sheet

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#13]
I'm working on a PC check macro. If you're interested, you could improve it.

<https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Savage%20Worlds/Verifica%20Ficha.js>

![image](https://user-images.githubusercontent.com/4999783/117600432-48019600-b122-11eb-8b33-bee0a38a1cc9.png)

**Comment by SalieriC** [comment]
So your macro tries to verify whether or not a character was created according to the rules?
I think there's space for that in SWIM. You'd need to translate it though I'm afraid as I can't do that myself and I can only guess what the message reads. ^^'

**Comment by brunocalado** [comment]
[Verifica Ficha - Copia.txt](https://github.com/SalieriC/SWADE-Immersive-Macros/files/6452189/Verifica.Ficha.-.Copia.txt)

**Comment by SalieriC** [comment]
I think there are way too many rules to consider, especially when it comes to supporting settings and so I don't think the benefits will outweigh the amount of work involved.
