### ISSUE TITLE
[BUG] "Error Occurring During Module Update: SWADE Immersion Module"

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#131]
**Describe the bug**
Whenever I click on "Update Modules," I consistently encounter the same error messages as shown in the attached images. I suspect there may be an issue with the manifest.json file or possibly with the Foundry VTT packages website.

**To Reproduce**
1. Go to the module management section.
2. Click on "Update Modules."
3. Scroll down to view the error messages displayed.

**Screenshots**
![image](https://github.com/SalieriC/SWADE-Immersive-Macros/assets/4999783/86058163-88b3-4bf5-a039-903497a5f87b)
![image](https://github.com/SalieriC/SWADE-Immersive-Macros/assets/4999783/1e80aa10-5e2b-4c0f-aa0b-dae8fea84409)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome
 - FVTT Version: 11
 - SWADE System Version: 304
 - SWIM Version:  150

**Comment by SalieriC** [comment]
Thank you for your report.
Please be aware that the module is currently not released for FVTT v11. That said, I will take a closer look at the dependencies and make sure they are pointing to the right direction. In the meantime I'd like to advise you to be cautious when using SWIM on v11. I had to fix a couple bugs. The v11-ready release is scheduled for the very near future though.

**Comment by SalieriC** [comment]
I've made some changes to the dependencies which should fix it but there is no way to test this without a release. Please reopen this if the issue persists after the v11 update (which will likely happen this weekend.
