### ISSUE TITLE
[BUG] Health Centre dialog showing "undefined"

### ISSUE THREAD

**Issue by steveculshaw** [SalieriC/SWADE-Immersive-Macros#135]
**Describe the bug**
The Health Centre dialog is showing "undefined" ...

<img width="323" alt="image" src="https://github.com/SalieriC/SWADE-Immersive-Macros/assets/64320/121b2896-6548-4569-8474-be9a6425a67f">

and here ...

<img width="319" alt="image" src="https://github.com/SalieriC/SWADE-Immersive-Macros/assets/64320/5cbbec6b-bbd5-404d-88ac-e9a3ff3891e5">

and an extra $ here _(characters name is Falco, not $Falco)_ ...

<img width="223" alt="image" src="https://github.com/SalieriC/SWADE-Immersive-Macros/assets/64320/7d7eaec8-4228-4ac5-8c83-35710af952fc">

**Comment by SalieriC** [comment]
Yeah, the `$` is definitely an oversight from localisation and confirms my suspicion. Should be an easy fix. Thanks fro the report. =)

**Comment by SalieriC** [comment]
Should be fixed in the next version. If you can please download the main branch and try for yourself. If more errors like this appear please reopen this ticket. Thanks. =)
