### ISSUE TITLE
BR2 Ammo Macro broken [BUG] 

### ISSUE THREAD

**Issue by loofou** [SalieriC/SWADE-Immersive-Macros#136]
**Describe the bug**
I just noticed that the Ammo Macro for BR2 is broken, because they changed the flags structure. `trait_rolls` for example is now no longer under `render_data` but instead under `br2_data`.

**To Reproduce**
1. Shoot any weapon with the Ammo Macro enabled
2. Look at console error ;)

**Expected behavior**
Ammo Macro works again like expected.

If I find the time I can provide a PR for the fix. I should have a bit of time tomorrow, so maybe I can go over it, unless you already fixed it until then :)

**Comment by SalieriC** [comment]
Yes, Javier did tell me about it in advance but I haven't found the time to dig into it yet. Feel free to look into it if you have time. Javier mentioned it'd be an easy fix.
