### ISSUE TITLE
Travel Calculator crashes when no encounters are loaded

### ISSUE THREAD

**Issue by mysurvive** [SalieriC/SWADE-Immersive-Macros#139]
**Describe the bug**
The travel calculator macro crashes when there are no encounters loaded in the settings with the error "cannot read properties of undefined (reading 'checked'). 
![image](https://github.com/SalieriC/SWADE-Immersive-Macros/assets/16602055/1ff598e3-8ead-471e-becb-0104e93ccfa6)
![image](https://github.com/SalieriC/SWADE-Immersive-Macros/assets/16602055/daef5762-1cf9-4f8f-8657-eef40c7101e9)

**To Reproduce**
1. Create a new world
2. Run the travel calculator macro
3. Macro crashes
4. 
![image](https://github.com/SalieriC/SWADE-Immersive-Macros/assets/16602055/599759ba-5db8-46bc-8ad2-87521a66e49d)

**Expected behavior**
The macro appears to have *optional* encounters, so having no encounters loaded seems like a logical, correct, and valid way of running the macro.

**Screenshots**
Several screenshots posted.

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Chrome and Foundry Native App
 - FVTT Version: 11.307
 - SWADE System Version: 3.0.6
 - SWIM Version:  2.1.0
 - Other Modules enabled?:  no

**Additional context**
I already submitted a PR for the fix, I got ahead of myself and didn't see you wanted an issue first.

**Comment by SalieriC** [comment]
Thank you for your time and efforts. =)
Did [my commit here](https://github.com/SalieriC/SWADE-Immersive-Macros/commit/6e572d6f39277463690e7c1202be66404d8a2305) not fix the issue for you? I cannot reproduce that error with it. Note that the code on git is more recent than the release.
I suppose your PR wouldn't hurt, I just wonder if I'm missing something here.

**Comment by mysurvive** [comment]
That's totally my fault for not pulling from github and instead just opening the latest module release! That looks like it'll work (and is much more elegant than my solution :) ), I can test it this evening and report back.

**Comment by mysurvive** [comment]
Coming back to report that the fix is working _swim_mingly (forgive me, I had to do it). I'll close the PR!

**Comment by SalieriC** [comment]
No problem mate, I highly appreciate your time. Please feel free to help improve SWIM further in the future if you like and find something that could be improved. =)
Also, you are forgiven for the pun on the name. Both SWIM and SUCC have their abbreviations chosen deliberately to allow for puns anyway. :D
