### ISSUE TITLE
Healing macro support Healing skill

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#14]
Can you to the Healing macro the rule for skill?

The player target a token and then can use the macro to roll the test, and auto apply the healing or damage.

p98: `The Healing skill is used to remove Wounds.
Each attempt requires 10 minutes per wound
level of the patient. Subtract 1 from Healing
rolls without a basic First Aid kit or similar
supplies.`
`A success removes one Wound, and a raise
removes two. Failure means no Wounds
are removed. A Critical Failure increases the
victim’s Wound level by one.`

**Comment by SalieriC** [comment]
ATM not. BUT I think it could be done. I need to learn more about targeting though. The question is: Can you update a token you do not own by executing a macro? I'm not sure right now. Also I don't yet know how to utilise the target stuff. I could use some help with that.

**Comment by brunocalado** [comment]
```js
//Get target
let tokenTarget=Array.from(game.user.targets)[0];
//read data from target
let currentWounds = tokenTarget.actor.data.data.wounds.value;
//change value from target
tokenTarget.actor.update({ "data.wounds.value": 2 });
```

**Comment by SalieriC** [comment]
Great, I'll take a look at it. Thank you.
Will probably be more than just another function. I'm thinking of replacing the original dialogue if there is a target. I also have way too many ideas for this. Like integrating the skill, the spell and giving away potions... Will likely start small though. Good suggestion nontheless.

**Comment by SalieriC** [comment]
I'm not sure I can reasonably fit this into the existing macro. I either need to completely refactor it (urgh) or create a new macro for healing others. That'd be faster but less convenient. Gotta think about it.

**Comment by SalieriC** [comment]
I can't find a way I am satisfied with. The problem is, that players obviously aren't allowed to edit other actors unless they have owner permission. So either the GM has to run the macro (and then there is no need for this anyway) or all players need owner permission on all other characters what I really despise personally as it reveals the sheet, opens new ways for human error (i.e. accidentally editing other players characters) and shares vision with everyone else.
I'm open for suggestions here as I am at my wits end.

**Comment by SalieriC** [comment]
The PHC now supports healing of others and even use of the healing skill during combat. It still requires the user to make the roll first but that's something I may get to later. I will create a new ticket for that.
