### ISSUE TITLE
[BUG]  Shapechanger Macro no longer working correctly.

### ISSUE THREAD

**Issue by Deadlander** [SalieriC/SWADE-Immersive-Macros#141]
**Describe the bug**
When using the Shapechanger macro, it will create the new actor, but will not replace the current actor and throws a large error in the console.

**To Reproduce**
1. Start Game. Place Actor token.
2. Click on actor token.
3. Activate Shapechanger macro.

**Expected behavior**
The shapechange should happen. 

**Screenshots**
Here is the error:

![image](https://github.com/SalieriC/SWADE-Immersive-Macros/assets/13036735/5143e120-3dc5-440e-a675-31829f46683a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - FVTT Version: 11.315
 - SWADE System Version: 3.2.3
 - SWIM Version:  2.3.0
 - Other Modules enabled?:  No

**Additional context**

**Comment by SalieriC** [comment]
Careful investigation revealed a faulty actor to be to blame here, not an error in SWIM.
