### ISSUE TITLE
[BUG] The Mighty Summoner macro creates a token with the Disposition set to Hostile

### ISSUE THREAD

**Issue by steveculshaw** [SalieriC/SWADE-Immersive-Macros#142]
**Describe the bug**
The Mighty Summoner macro creates a token with the Disposition set to Hostile

**To Reproduce**
1. Run the Mighty Summoner macro
2. Check the new tokens Disposition

**Expected behavior**
The token should be created with the same Disposition as the summoner

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - FVTT Version: 11.315
 - SWADE System Version: 3.2.5
 - SWIM Version:  2.3.0

**Comment by SalieriC** [comment]
Yeah, I think it retains the disposition of the original because at the time it was kinda intended for PC use only. I'll get to it.

**Comment by SalieriC** [comment]
Should be fixed in the upcoming release.
