### ISSUE TITLE
[BUG]  On Hold not working anymore after the first round

### ISSUE THREAD

**Issue by Arnok13** [SalieriC/SWADE-Immersive-Macros#146]
After the first round, with SWADE 3.3.6 (may be 3.3.x) the On Hold status act weirdly in the Turn Order. Character, On Hold are changer immediately to the first rank of the turn order. When the character want to act now or efter the current turn order (new button form the system) the current turn goes back to the previous character.
Can be linked to Quick and Level-Headed character either.

**Expected behavior**
Turn order stay in their rank in the current round. When a character act now (i win the Athletics opposite roll) the turn order must be set on him.

**Screenshots**
video linked :  https://cdn.discordapp.com/attachments/715780900322803753/1220097628348616764/2024-03-20_20-51-21.mp4?ex=660db376&is=65fb3e76&hm=058f229beb06a5770e7e8823629e8616271c0d7896482fc494bdc358d520b93b&

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Browser: directly in Foundry (seen with Edge and Opera too)
 - FVTT Version: 11.315
 - SWADE System Version: 3.3.6
 - SWIM Version:  2.4.0
 - Other Modules enabled?:  deactivated to just let SWIM act.

**Additional context**
posted a video to show the behavior in the Foundry SWADE Discord (try to put it there).

**Comment by SalieriC** [comment]
Thank you for your comprehensive report.
SWIM isn't ready for SWADE 3.3.x yet which brought a lot of new and overhauled changes, especially to initiative so problems there are expected. I think the best course of action now is just to remove the feature from the module as the system finally provides a native way of handling this. I am working on a new version and it should hopefully be ready shortly. So please stay tuned for an update. If you can't wait I'd suggest disabling SWIM or rolling back the world and the system to 2.2.x.

**Comment by SalieriC** [comment]
On closer look, this seems to be related to the 3.3.6 addition that followers can go on hold independently of their leader. In 3.3.3 it was working as intended. I would have to take a closer look at the exact changes but it seems leader and follower are connected in another way now than they were before.
Also SWADE missed the opportunity to allow players to go on hold on their own so the function in SWIM is still relevant as it allows players to go on hold on their own without the need of the GM doing so. But updating everything to restore the intended behaviour may need more time and I'm not sure I can come up with a decent solution. So it really pains me but I think I'm going to sunset the feature.
