### ISSUE TITLE
Read Tables from Compendium

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#15]
Hi!

Can you make the settings support read tables from a compendium? 

Thank you.

![image](https://user-images.githubusercontent.com/4999783/118182498-77105400-b40f-11eb-98f0-f50975794ecb.png)

**Comment by SalieriC** [comment]
Possibly. I think I could make three drop down menues to select the source (world/compendium), compendium and table in there. I just ask myself whether the improvement would be worth the effort tbh. Why is importing the table not a good option for you?

**Comment by brunocalado** [comment]
I take everything I can out of the world and play in compendiums.

This is recommended for performance.

And if it is compendium you can only point to the one of the SWADE module.

**Comment by SalieriC** [comment]
I guess I never had enough entities to really notice a decrease in performance. I'll see what I can do. No promises though. I have a few big things coming soon which take priority.

**Comment by brunocalado** [comment]
I used the Fantasy Grounds Converter for pf2.

It creates thousands of entities in the world.

It took me some time to find out about it.

After that, I avoid everything I can in the world.

**Comment by SalieriC** [comment]
If you have any idea as to how to do it, be my guest to create a PR. Can't research it on my own at a later time though.

**Comment by SalieriC** [comment]
I get the concern but I think with the recent changes to FVTT it got clear that stuff in compendiums isn't supposed to be used. I'm closing this now. If the situation gets changed I will reconsider.
