### ISSUE TITLE
Deviation

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#17]
If you're interested you could add this macro too.

![image](https://user-images.githubusercontent.com/4999783/118378868-e66f7a80-b5ac-11eb-89d4-d3a2947d8972.png)

link: <https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Savage%20Worlds/Deviation.js>

**Comment by SalieriC** [comment]
Good suggestion, thank you. =)
Is the image made by yourself? If not I need a source and the license. If it is made by yourself, I guess you're fine using it here. However I'd like to include it in the assets of SWIM.

**Comment by brunocalado** [comment]
It's modified from: https://freesvg.org/

**Comment by brunocalado** [comment]
I want to be able to draw the template. But, I don't know how.

It'll be cool target a token and it draws the template based on target position.

**Comment by SalieriC** [comment]
> I want to be able to draw the template. But, I don't know how.  

I wanted to do that for many purposes for a long time now. No luck as of yet. -.-
Anyway, I hope I will be able to integrate this macro (well, part of it) in my current project:

**Comment by SalieriC** [comment]
Will not be part of the ammo mgm for now due to lack of time.
