### ISSUE TITLE
Mass Battle

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#19]
Link: https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Savage%20Worlds/MassBattle.js

![image](https://user-images.githubusercontent.com/4999783/118401557-86281980-b63c-11eb-9483-703ff01ab34f.png)

**Comment by brunocalado** [comment]
Hi. What do you think about this one?

**Comment by SalieriC** [comment]
I have yet to test it. It's one of the more complex ones I think and it'll probably take some time to review it. That being said, I don't like the idea too much. Too much automation for my taste. But that alone won't stop me from implementing it as others might find it useful. I need to take a closer look at it but that'll probably take its time as I unfortunately lack the time to work as much on Foundry stuff as I'd like to atm. :-S
But: Thank you very much for all your contributions, they are much appreciated; keep up the good work mate. =)

**Comment by SalieriC** [comment]
I think it's awesome but a bit too automated for my taste. I do Mass Battles in a far more immersive way and I think this distracts a bit from that. But everyone who just wants to get done with a Mass Battle is surely going to love it.
