### ISSUE TITLE
Add Size & Scale Macro

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#21]
Hi.

One more macro: <https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Savage%20Worlds/SizeScaleCalculator.js>

![image](https://user-images.githubusercontent.com/4999783/119160051-3e373700-ba2e-11eb-94d2-2aac44763f57.png)

**Comment by SalieriC** [comment]
Saw this one on the BR repo. I like it a lot. I will also add a notice about Swat if the creature has it though.

**Comment by brunocalado** [comment]
What is SWAT?

Can you share the outcome back so I can update mine?

Tks

**Comment by SalieriC** [comment]
See SWADE p. 178

Sure. I'll
- [ ] add swat support
- [ ] inform @brunocalado when done

;-)

**Comment by SalieriC** [comment]
Okay, swat support is working. I now just need to tweak the chat message a bit more. But this is all I have time for today I'm afraid.
![image](https://user-images.githubusercontent.com/1230041/119320071-77b0b200-bc7b-11eb-941e-4c3aaa41f8a5.png)

**Comment by brunocalado** [comment]
Great. After you finish I'll share it back to Better2.

**Comment by SalieriC** [comment]
What do you think @brunocalado ?
![image](https://user-images.githubusercontent.com/1230041/119377383-5a043c80-bcbd-11eb-8cd2-8db42666bff8.png)
underlined red text is clickable and leads to entries from the core rules. If the core rules module is not installed, it will show the message without links. Will push it soon-ish unless you think something should be changed.
I originally wanted to make the `Swat` in the results a link leading to the actors owned item but that is not possible in macros. @javierriveracastro would be able to do just that.

**Comment by brunocalado** [comment]
Perfect. Nice job!

**Comment by SalieriC** [comment]
There was a discussion on it over at the Better Rolls repo. Anything to fix here?
https://github.com/SalieriC/SWADE-Immersive-Macros/blob/main/swim/macros/Scale%20calculator.js

**Comment by brunocalado** [comment]
I pushed one update to add swat to the calc function. I did that for the grap macro I'm working on.

![image](https://user-images.githubusercontent.com/4999783/120127244-3d707480-c195-11eb-8ff8-50320e799237.png)


![image](https://user-images.githubusercontent.com/4999783/120127195-1e71e280-c195-11eb-8f23-5a722c6ebbfc.png)

**Comment by SalieriC** [comment]
The thing is, that you can't add Swat to the calculation. Otherwise I would've done that. Swat only works for selected attacks specified in the description on Swat. Since it does not apply to all actions it can't be done unless the actions are marked as such. But the system currently has no way of doing that.
