### ISSUE TITLE
Gang Up

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#22]
Hi.

Can try to add Gang Up macro? Thank you

![image](https://user-images.githubusercontent.com/4999783/119509939-751b8e80-bd47-11eb-90f5-6267c10b6e59.png)

Macro: https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Savage%20Worlds/GangUp.js

**Comment by brunocalado** [comment]
There is second version ready for JB2A.

https://user-images.githubusercontent.com/4999783/119569062-9babea80-bd84-11eb-9e49-368ce57a4dc8.mp4

**Comment by SalieriC** [comment]
Gang up is a very tricky rule in SWADE (and was in earlier versions as well). I doubt that a macro can reliably handle this. But I will try it before making a final decision. This is low priority though.

**Comment by brunocalado** [comment]
Fantasy Grounds can treat gang up. I think we can too.

This macro is not finished. There is some problems. I'll work on it soon.

**Comment by brunocalado** [comment]
This macro is working well now.

**Comment by SalieriC** [comment]
I think it's somewhat out of scope for SWIM. But thanks a lot for the suggestion. =)
