### ISSUE TITLE
Grappling

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#26]
Macro: https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Savage%20Worlds/Grappling.js

![image](https://user-images.githubusercontent.com/4999783/120204434-30886b00-c1ff-11eb-8b6a-06b6e7a1cc5f.png)

**Comment by SalieriC** [comment]
Depends on whether or not I decide to implement #22.Still on the fence here.

**Comment by SalieriC** [comment]
Okay, two questions @brunocalado:

1. Is this still up to date?
2. Does it require the ganging up macro or is it self-sufficient?

**Comment by brunocalado** [comment]
Broke
