### ISSUE TITLE
Add Settings Extender and Compendium Folders to the dependencies and check for those on initialising FVTT

### ISSUE THREAD

**Issue by gravagehulk** [SalieriC/SWADE-Immersive-Macros#31]
On 8.9, I didn't have this issue. After updating to 9, whenever I try to click on the "configure settings" button to change module or system settings, nothing happens and I get this console error. Disabling SWIM allows the settings button to work again:

![image](https://user-images.githubusercontent.com/69117052/149572706-2c2c5e16-3323-4383-a4a8-8a8593c57f04.png)

Edit: I just realized after reading the error more closely, that I didn't have "settings extender" enabled. That fixed it. Sorry about that.

**Comment by SalieriC** [comment]
No worries, you did very well and I'll reopen this issue because settings extender is not in the dependencies as well as compendium folders, which I need to fix, so thank you for bringing this to my attention. =)

**Comment by gravagehulk** [comment]
Awesome. Glad I could help!

**Comment by SalieriC** [comment]
Done. Thanks again for bringing it to my attention. =)
