### ISSUE TITLE
Make macros affect all targeted & selected tokens

### ISSUE THREAD

**Issue by SalieriC** [SalieriC/SWADE-Immersive-Macros#33]

**Comment by SalieriC** [comment]
I need help here: Would that actually be a good idea? The macros are capable to play SFX on becoming Shaken for example. affecting multiple tokens would mean loosing some of that. Like playing only the SFX for one token, not all of them. But then I'd need to make a selection on which SFX to play.
So my question is: Would it be so very helpful to mark multiple tokens as Shaken that it outweighs the loss of SFX for you?

**Comment by grendel111111** [comment]
would it then be a GM only macro?

**Comment by SalieriC** [comment]
No, I don't think that would be helpful. Players sometimes also have extras so this feature could - in theory - be beneficial for everyone.

**Comment by grendel111111** [comment]
I personally think it would be great.

**Comment by Deadlander** [comment]
Why not keep the ones that do the SFX, but add the one that loses the SFX but does the multi-target?

**Comment by SalieriC** [comment]
> Why not keep the ones that do the SFX, but add the one that loses the SFX but does the multi-target?

That would be my last resort. I want to keep the amount of code that basically does the same as low as possible. This is what I'll be working on in the next time. Reason being that whenever I do a change or update to a new FVTT version, I have to apply the same changes over and over again. This costs time and is not a fun thing to do.
Also I want to avoid cluttering the macro bar. There is only so much space there. I would much prefer to do it in the same macro.

**Comment by grendel111111** [comment]
Would an option be to check if multiple targets or selects are made and only add the sound when there is only 1 selection?

**Comment by Arnok13** [comment]
never really use multi-shaken action (quite rare with swade, non ?).

**Comment by SalieriC** [comment]
I can't decide for now. Will contemplate on your opinions a bit more first. Thank you for your help though. =)

**Comment by pmoore603** [comment]
I'm not quite understanding the problem.  What macro(s)?  And, for example, what needed to change with a FVTT update?

**Comment by SalieriC** [comment]
> I'm not quite understanding the problem. What macro(s)? And, for example, what needed to change with a FVTT update?

As of SWIM v. 0.15.0 this changes to the script and I can somewhat mitigate some of the older problems. But still, I need to spend a significant amount of my time maintaining the code whenever a new FVTT version is released as there are always deprecations that break my code. This is one of the reasons why I wanted to pull functions out of my scripts and make them available for all the scripts at one place. This has now started. I will need to spend more time pulling out parts that are shared across scripts. When this is done I can maintain stuff once, instead of multiple times for each part of the module.

**Comment by SalieriC** [comment]
I've decided against it. Some macros will have that (like the mark dead macro) but others won't. It's a mixture of too much work and workarounds combined with somewhat limited use.
