### ISSUE TITLE
Libwrapper error

### ISSUE THREAD

**Issue by gravagehulk** [SalieriC/SWADE-Immersive-Macros#35]
Since the last update, I'm getting this error when I try to enable/disable modules. As you can clearly see, I have Libwrapper installed and enabled. I have tried toggling SWIM off and on and other things, but this error never goes away.

![image](https://user-images.githubusercontent.com/69117052/149635974-aedd52fc-5790-421c-8b01-67033890a1bf.png)

**Comment by loofou** [comment]
Yes, have the same issue. I think something is off with the way libWrapper is referenced as a dependency.

**Comment by SalieriC** [comment]
Thank's for letting me know. I've created a hotfix for this, now available through foundry or here as a direct download:
https://github.com/SalieriC/SWADE-Immersive-Macros/releases/tag/v.0.12.3
This should solve it. Please reopen this issue in case it doesn't.
