### ISSUE TITLE
[Suggestion] Chase Setup script

### ISSUE THREAD

**Issue by pmoore603** [SalieriC/SWADE-Immersive-Macros#39]
I added some fields to let the GM customize size and location of the chase deck.  See attached file.

[ChaseSetup.txt](https://github.com/SalieriC/SWADE-Immersive-Macros/files/8228947/ChaseSetup.txt)

**Comment by SalieriC** [comment]
Please make a pull request so I can properly review the code, thanks. =)

**Comment by pmoore603** [comment]
I think I've done it properly...
The 0.8.9 script tests properly, but I'm not able to test the 0.9.0 "prep" version.

First github pull request ever for me!
