### ISSUE TITLE
Shape-change token loses elevation setting

### ISSUE THREAD

**Issue by pmoore603** [SalieriC/SWADE-Immersive-Macros#58]
I was able to retrieve the elevation in the code, and was able to store it in `scCopy`, but the value is lost after `scCopy.createEmbeddedDocument` in the `update_preset` function.  My guess is that a `token` somewhere during this process is `PrototypeTokenData` (which does NOT have elevation) and is not `TokenData` (which does have elevation).  I can get this to work by getting the elevation at the start of `main()` and passing it in as an argument to `replace_token()` and doing this at the end of the function:

```
let newToken = canvas.tokens.get(newTokenID[0])
await newToken.document.update({'elevation': elevation})
```

**Comment by SalieriC** [comment]
I rarely use elevation which is why I forgot about it initially.
Done in git. Thanks for the code snippet. =)
