### ISSUE TITLE
Missing translatable strings

### ISSUE THREAD

**Issue by Razortide** [SalieriC/SWADE-Immersive-Macros#62]
Hello @SalieriC,

after firing the first draft up on my test system I've found a few missing strings:

SWIM Settings Tabs (Setting Rules, Item Options, Roll Tables, Chase Layout, SFX & VFX Options, Additional Conditions)
Default values natural healing: five days, Potion names healing and remove fatigue, table names.

A general question: Shall we generally use colons or shall we remove them? From my point of view I would remove the colons.

**Comment by SalieriC** [comment]
The colon is important, otherwise the letters will run away as my teacher always said. 🤣 

As for the translation strings, they'll be added. They shouldn't affect functionality unless players do not change them, right?

**Comment by SalieriC** [comment]
Now that the module is fully functional in other languages, #6 is the hub for all translation discussions.
