### ISSUE TITLE
Personal health centre not working

### ISSUE THREAD

**Issue by Warwomble** [SalieriC/SWADE-Immersive-Macros#67]
Hi 

The personal health centre does not seem to be working for me anymore.
If I click on it it tells me to select a token but when I select a token nothing happens.

Thanks
C

**Comment by SalieriC** [comment]
That is already fixed in git: https://github.com/SalieriC/SWADE-Immersive-Macros/blob/main/CHANGELOG.md#fixed
> A bug that caused the PHC to break because of a faulty setting string.

I hope to release it tomorrow. Sorry for the inconvenience.

**Comment by Warwomble** [comment]
Great have run the update and it now works perfectly thanks.
