### ISSUE TITLE
Ammo Management chat card error

### ISSUE THREAD

**Issue by peterptero** [SalieriC/SWADE-Immersive-Macros#79]
Chat card prints "SWIM.chatMessage-ReloadWeaponWithAmmoName” on reload. 

- Ammo in inventory is still deducted correctly. 

- The chat card prints the correct message if the weapon reloads with a different ammo type, but not if it's reloaded with a consecutive ammo type.

**Comment by SalieriC** [comment]
Fixed by @Razortide (#77) and published in version 0.17.1.
Thanks for reporting. =)
