### ISSUE TITLE
[FEATURE] Auto-Favorite Spell Effects with Effect Builder

### ISSUE THREAD

**Issue by Razortide** [SalieriC/SWADE-Immersive-Macros#85]
**Is your feature request related to a problem? Please describe.**
I just found that when you apply Spell effects with the Effect Builder they are hidden away in the effects tab.

**Describe the solution you'd like**
I guess since these temporary effects should be present it would be great if the Effect Builder would "auto-star" the Effects they apply so they are visible on the main page.

**Comment by SalieriC** [comment]
I've considered that. The thing is: I don't want to force that on users. Each user should be able to configure this themselves. I could add a checkbox on the PEB to make that but that's kinda clunky I think on the other hand it allows users to do this for each power individually. Another idea would be to configure this on each actor.
I'd like to hear your feedback @Razortide and the feedback of the community as a whole on the matter.

**Comment by SalieriC** [comment]
This seems to be default in SWADE or Foundry now so I'll close it.
