### ISSUE TITLE
[FEATURE] Add Power to Source of Active Effect

### ISSUE THREAD

**Issue by Razortide** [SalieriC/SWADE-Immersive-Macros#86]
**Is your feature request related to a problem? Please describe.**
If you click on the Effects that have a source the source will be opened. The Builder does not create the Effect with a Source.

**Describe the solution you'd like**
If it is possible, the Source power should be linked, that way you can "click through" to the Power directly and have the information right on your fingertips.

**Comment by SalieriC** [comment]
This requires some work over at SUCC which I won't be able to do very soon I'm afraid. I'll try to cover it asap though.

**Comment by SalieriC** [comment]
Turns out it's a veeeery bad idea to mess with that. I just blew an actor to smithereens trying to do this. I'm not a 100% sure what the requirements are here. Just entering the items ID doesn't seem to do it. If anyone has insight in this please tell me. Otherwise I'll close this as won't fix.

**Comment by SalieriC** [comment]
Yeah sorry, I can't get it to work for whatever reason. :-S
