### ISSUE TITLE
Shape Change seems to not work [BUG] 

### ISSUE THREAD

**Issue by Portacustos1** [SalieriC/SWADE-Immersive-Macros#98]
I've tried this with and without the blending options as I saw the other bug report, however this seems to be a different issue.

When trying to use the Shape Change Macro it just doesn't seem to work. Initially it flagged up the error as I didn't have the folders set up, and then I got the message for not having a token selected, so it's doing something, however no change occurs and no error pops up. I've included the picture of the error in the console log (means nothing much to me), the module is up to date (via Forge) and below is the support report for the version I'm on.

<img width="377" alt="Shape Change Errors" src="https://user-images.githubusercontent.com/85347717/197878227-7e173d3f-abed-4cf1-a9d9-14a3f090a9ef.PNG">

> Foundry Virtual Tabletop: Version 10, 10.288
> Game System: swade, 2.0.6
> Active Modules: 83
> Performance Mode: 2
> 
> OS: Unknown
> Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
> GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)
> Max Texture Size: 16384
> 
> Scene: 9200 x 12000 | Grid Size: 200 | Padding Percentage: 0.25
> Walls: 76 | Ambient Lights: 3 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 12
> 
> Actors: 300 (1 Invalid) | Items: 20 | Journal: 406 | Rollable Tables: 33 |
> Playlists: 9 | Compendium Packs: 66 | Chat Messages: 398

**Comment by SalieriC** [comment]
Thank you for your report.
Please note that you are using SWIM with a currently unsupported version of Foundry. Our development version already has that covered. Please be patient for a few more days, the v10 ready SWIM version will be available shortly. As always, I will announce a new release on the official discord and here on this repo.
Thank you for taking the time to reach out to us.
